# ç½‘ç«™ä¸»é¡µæ ‡é¢˜
title: æœªæ¥ç«™
# ç½‘ç«™æ ‡é¢˜åç¼€
suffix: future
# ä½œè€…åç§°(ä¼šæ˜¾ç¤ºåœ¨é¦–é¡µæ–‡ç« ä¸‹é¢)
author: threemoreliu
# ç½‘ç«™å…³é”®å­—
keyword: Hexo theme, blog
# ç½‘ç«™æè¿°
web_description: ğŸ“enjoyFreetime.
# ç½‘ç«™è¯­è¨€
lang: zh-CN
# ç½‘ç«™å»ºç«™æ—¶é—´
since_year: 2024
# å¯¼èˆªåç§°
menus_title:
    home: ä¸»é¡µ
    categories: ç±»åˆ«
    tags: æ ‡ç­¾
    archives: å½’æ¡£
    galleries: ç›¸å†Œ
    links: é“¾æ¥
    about: å…³äº

# å¯¼èˆª
menus_link:
    home: /
    categories: /categories
    tags: /tags
    archives: /archives
    galleries: /galleries
    links: /links
    about: /about

# ä¸ªäººä¿¡æ¯
about: 
    author: threemore
    portrait: 'https://gz-metal-cell.github.io/about/portrait.png'
    description: 'move forward!!!'

# logo
logo: /images/headers_icon/logo.webp
# Icon
icon:
    favicon: /images/icon/favicon.ico # ç½‘é¡µæ ‡ç­¾ä¸Šé‚£ä¸ªå°å›¾æ ‡ ä¸€å®šè¦ç”¨æœ¬åœ°å­˜å‚¨
    locked: /images/icon/locked.png
    normal: /images/icon/normal.png
    go_top: /images/icon/go_top.png
    go_bottom: /images/icon/go_bottom.png
    search: /images/icon/search.png
    aside: /images/icon/aside.png
    toggle_theme: /images/icon/toggle_theme.png
    copy: /images/icon/copy.png
    close_code_block: /images/icon/close_code_block.png
    sticky: /images/icon/sticky.png

# æ¯ä¸ªé¡µé¢çš„å±•ç¤ºçš„å›¾æ ‡å’Œä¸€å¥è¯
headers:
    home:
        {
            message: "å±…ç„¶è¢«ä½ æ‰¾åˆ°äº†è¿™é‡Œï¼",
            icon: "/images/headers_icon/logo_white.webp",
        }
    categories:
        {
            message: "å¥½åƒä¹Ÿæ²¡åˆ†å‡ ç±»",
            icon: "/images/headers_icon/categories.svg",
        }
    tags:
        {
            message: "è¿™é‡Œæ˜¯ä¸€äº›å±•ç¤ºçš„æ ‡ç­¾",
            icon: "/images/headers_icon/tags.svg",
        }
    archives:
        {
            # è¿™é‡Œä¼šæ›¿æ¢æ‰ä¸¤ä¸ªå˜é‡{ year å¹´ï¼Œnumber æ€»æ•° } å½“ç„¶ä¹Ÿå¯ä»¥ä¸å†™è¿™ä¸¤ä¸ªå˜é‡
            message: "å±…ç„¶ä¸€å…±æ‰å†™äº† number ç¯‡æ–‡ç« ï¼",
            message_month: "åœ¨ year å¹´ month æœˆé‡Œå†™äº† number ç¯‡æ–‡ç« ï¼",
            message_year: "åœ¨ year å¹´é‡Œå†™äº† number ç¯‡æ–‡ç« ï¼",
            icon: "/images/headers_icon/archives.svg",
        }
    galleries:
        {
            message: "æœ‰è¶£çš„ç›¸å†Œ~ï¼ˆæ–½å·¥ä¸­ï¼‰",
            icon: "/images/headers_icon/galleries.svg",
        }
    links:
        {
            message: "ä¸€äº›ç¥å¥‡å°ç½‘ç«™~",
            icon: "/images/headers_icon/links.svg",
        }
    about:
        {
            message: "å…³äºæˆ‘",
            icon: "/images/headers_icon/about.svg",
        }

# ç½‘é¡µè®¿é—®ç»Ÿè®¡
web_analytics:
    enable: true  # éœ€è¦æ”¹ä¸º true
    busuanzi: true  # ä¸è’œå­è®¿é—®é‡ç»Ÿè®¡
    baidu:  #ï¼ˆæ›¿æ¢ï¼‰ç™¾åº¦ç»Ÿè®¡çš„ Keyï¼Œå‚è§ https://tongji.baidu.com/sc-web/10000033910/home/site/getjs?siteId=13751376 ä»£ç è·å–ä¸­ hm.js? åè¾¹çš„å­—ç¬¦ä¸²

# Giscus
# é…ç½®æ–¹æ³•è¯¦è§ https://giscus.app/
giscus:
    enable: false
    repo: 
    repo_id: 
    category: Announcements
    category_id: 0
    mapping: title
    strict: 1
    reactions-enabled: 1
    emit_metadata: 0
    input_position: bottom
    # loading: lazy

# gitalk è¯„è®º
gitalk:
    enable: true
    clientID: Iv23liJaVpIqP0J1RupK
    clientSecret: 00feff266e1a152133d59c6deecf75c5930075fe
    repo: threemoreliu.github.io
    owner: threemoreliu #ï¼ˆéœ€è¦æ›¿æ¢ï¼‰GitHub repository æ‰€æœ‰è€…ï¼Œå¯ä»¥æ˜¯ä¸ªäººæˆ–è€…ç»„ç»‡ã€‚
    admin: threemoreliu #ï¼ˆéœ€è¦æ›¿æ¢ï¼‰GitHub repository çš„æ‰€æœ‰è€…å’Œåˆä½œè€…ï¼ˆå¯¹è¿™ä¸ª repository æœ‰å†™æƒé™çš„ç”¨æˆ·ï¼‰ã€‚

# åº•éƒ¨æ˜¾ç¤ºçš„å›¾æ ‡ï¼ˆgithub æˆ–è€…å…¶ä»–ï¼‰
bottom_icon:
    # å¯ä»¥å¤šä¸ª
    - {
          # æè¿°åç§°
          name: "weibo",
          # å›¾æ ‡
          icon: "/images/bottom_icon/Weibo.webp",
          # è·³è½¬é“¾æ¥
          link: "",
      }
    - {
          # æè¿°åç§°
          name: "bilibili",
          # å›¾æ ‡
          icon: "/images/bottom_icon/Bilibili.webp",
          # è·³è½¬é“¾æ¥
          link: "",
      }
    - {
          # æè¿°åç§°
          name: "github",
          # å›¾æ ‡
          icon: "/images/bottom_icon/github.webp",
          # è·³è½¬é“¾æ¥
          link: "",
      }

# å½’æ¡£é¡µæ˜¯å¦å¼€å¯ä¾§è¾¹æ 
archive_aside: true
# æ ‡ç­¾é¡µæ˜¯å¦å¼€å¯ä¾§è¾¹æ 
tag_aside: true
# æ ‡ç­¾é¡µæ˜¯å¦å¼€å¯ç›®å½•
archive_toc: true
# æ ‡ç­¾é¡µæ˜¯å¦å¼€å¯ç›®å½•
tag_toc: true

# ç¿»é¡µæ˜¾ç¤ºä¸Šä¸‹æ–‡é¡µæ•°ï¼Œå¿…é¡»æ˜¯ä¸€ä¸ªè‡ªç„¶æ•°
pagination: 3

# æœç´¢ï¼ˆå¦‚æœ hexo-generator-search å¯ç”¨çš„è¯ï¼‰
search: true

# æ‡’åŠ è½½ï¼ˆå¦‚æœ hexo-lazyload-image å¯ç”¨çš„è¯ï¼‰
lazyload: false

# å­—æ•°ç»Ÿè®¡ï¼ˆå‰ç«¯æ–¹æ³•ï¼Œä¸éœ€è¦ hexo-wordcountï¼‰
wordcount: true

# è‡ªåŠ¨å°†å¤šä¸ªç©ºæ ¼æ›¿æ¢æˆå¯¹åº”çš„ &nbsp;
replaceSpacesWithNbsp: true

# fancybox
fancybox:
    enable: true
    css: css/plugins/fancybox.css
    js: js/plugins/fancybox.umd.js

# mathjax å’Œ katex ç”¨äºæ˜¾ç¤ºæ•°å­¦å…¬å¼ï¼ŒäºŒè€…å–å…¶ä¸€
mathjax:
    enable: false
    js: https://cdn.jsdelivr.net/npm/mathjax@4.0.0-beta.3/tex-mml-chtml.js

katex:
    enable: true
    css: /js/plugins/katex/katex.min.css # https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css
    js: /js/plugins/katex/katex.min.js # https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js
    auto_render: /js/plugins/katex/auto-render.min.js # https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js
    copy_tex:
        enable: true
        css: /css/plugins/copy-tex.css # https://cdn.bootcdn.net/ajax/libs/KaTeX/0.12.0/contrib/copy-tex.css
        js: /js/plugins/copy-tex.js # https://cdn.bootcdn.net/ajax/libs/KaTeX/0.12.0/contrib/copy-tex.js

# mermaid chart
# å¯ä»¥é…åˆï¼ˆhexo-filter-mermaid-diagramsï¼‰
mermaid: ## mermaid url https://github.com/knsv/mermaid
  enable: true  # default true
  js: https://cdn.jsdelivr.net/npm/mermaid@11.4.0/dist/mermaid.min.js
  options: # find more api options from https://github.com/knsv/mermaid/blob/master/src/mermaidAPI.js
    #startOnload: true  // default true

# é»˜è®¤çš„ cover (é»˜è®¤ç¼©ç•¥å›¾) åœ¨æ²¡æœ‰å¡«å†™ï¼ˆè¿™é‡Œå¯ä»¥æ›¿æ¢ï¼ˆå¯ä»¥æ˜¯ api ä¹Ÿå¯ä»¥æ˜¯å›ºå®šçš„å›¾ï¼‰ï¼‰
default_cover: "/images/random_top_img/01.webp"

# ç½‘é¡µçš„ top_imgï¼Œæ¯æ¬¡ä¼šä»ä¸‹é¢çš„åˆ—è¡¨ä¸­éšæœºé€‰å–ä¸€å¼ 
random_top_img:
    - "/images/random_top_img/01.webp"
    - "/images/random_top_img/02.webp"
    - "/images/random_top_img/03.webp"
    - "/images/random_top_img/04.webp"
    - "/images/random_top_img/05.webp"
    - "/images/random_top_img/06.webp"
    - "/images/random_top_img/07.webp"

# æ‰€æœ‰ç½‘é¡µä¸­æ’å…¥çš„ html è¯­å¥
inject: 
  head:
  bottom:

# å¦‚æœç½‘ç«™éœ€è¦å¡«å†™ ICP å¤‡æ¡ˆä¿¡æ¯ï¼Œå¯åœ¨è¿™é‡Œå¡«å†™
icp:
    enable: false
    icon: 
    link: 
    text: 

